#!/bin/sh

set -e

case "$1" in
		purge)
				rm -Rf "/etc/sites-available/ka-lite"
				rm -Rf "/etc/sites-available/ka-lite"
				rm -Rf "/etc/uwsgi/apps-available/ka-lite.ini"
				rm -Rf "/etc/uwsgi/apps-enabled/ka-lite.ini"
				rm -Rf "/tmp/ka-lite"
		;;
esac

exit 0

# vim: ts=2 sw=2
